version: '3'

services:
  app:
    build: .
    command: rails server -p 3000 -b '0.0.0.0'
    volumes:
      - .:/var/www/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  postgres:
    image: postgres:9.4
    ports:
      - "5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
