# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0a616913ddb4d11f80799938d7916a1544193296c5400c50a0232f3577e56924d7aa4824289412af8e934bb332d16c9959ac3bdd6771efaceb0439e5a2c6ae43

test:
  secret_key_base: 68db9c6028bb092b0ccd8accd9d98d5e789aef13f2eaff9a95147ff249a9f91ce4d1e6e5939dd8d4fe3c4d31eaadea10d91545ebf1c31284185235e7547785da

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
